In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.5.1+cu124


In [ ]:
if torch.cuda.is_available():
  print(f"{torch.cuda.get_device_name(0)}")
else:
  print("NO")

NO


In [ ]:
a=torch.empty(2,3)

In [ ]:
print(a)
print(a.type())

tensor([[2.2081e-32, 0.0000e+00, 1.1210e-44],
        [0.0000e+00, 8.9683e-44, 0.0000e+00]])
torch.FloatTensor


In [ ]:
type(a)

torch.Tensor

In [ ]:
b=torch.zeros(47,1)

In [ ]:
type(b)

torch.Tensor

In [ ]:
c=torch.rand(2,3)

In [ ]:
print(c)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [ ]:
print("using arange",torch.arange(0,10,2))
print(torch.linspace(0,10,10))
print(torch.eye(5))
print(torch.full((3,3),5))

using arange tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
a.shape

torch.Size([2, 3])

In [ ]:
torch.zeros_like(c)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.rand_like(c)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
c

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
c.dtype

torch.float32

In [ ]:
d=torch.tensor([1.0,2.0],dtype=torch.uint8)

In [ ]:
a=torch.ones(1,2)
b=torch.zeros(1,2)

In [ ]:
a+b

tensor([[1., 1.]])

In [ ]:
a*b

tensor([[0., 0.]])

In [ ]:
a-b

tensor([[1., 1.]])

In [ ]:
a*a

tensor([[1., 1.]])

In [ ]:
torch.abs(a)

tensor([[1., 1.]])

In [ ]:
torch.neg(a)

tensor([[-1., -1.]])

In [ ]:
torch.clamp(a,min=-1,max=2)

tensor([[1., 1.]])

In [ ]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.int64)
print(e)

tensor([[8, 8, 4],
        [4, 1, 0]])


In [ ]:
torch.prod(e,dim=1)

tensor([256,   0])

In [ ]:
torch.argmin(e)

tensor(5)

In [ ]:
torch.transpose(e,0,1)

tensor([[8, 4],
        [8, 1],
        [4, 0]])

In [ ]:
a>d

tensor([[False, False]])

In [ ]:
d>a

tensor([[False,  True]])

In [ ]:
torch.sqrt(e)

tensor([[2.8284, 2.8284, 2.0000],
        [2.0000, 1.0000, 0.0000]])

In [ ]:
torch.softmax(e,dim=1,dtype=torch.float32)

tensor([[0.4955, 0.4955, 0.0091],
        [0.9362, 0.0466, 0.0171]])

In [ ]:
torch.cuda.is_available()

False

In [ ]:
device=torch.device('cuda')

In [ ]:
torch.flatten(a)

tensor([1., 1.])

In [ ]:
b=torch.rand(2,3,4)

In [ ]:
torch.flatten(b)

tensor([0.2239, 0.3023, 0.1784, 0.8238, 0.5557, 0.9770, 0.4440, 0.9478, 0.7445,
        0.4892, 0.2426, 0.7003, 0.5277, 0.2472, 0.7909, 0.4235, 0.0169, 0.2209,
        0.9535, 0.7064, 0.1629, 0.8902, 0.5163, 0.0359])

In [ ]:
def dr_dx(x):
  return 2*x

In [ ]:
dr_dx(2)

4

In [ ]:
import torch
def dy_dx(x):
  return torch.sin(x)

In [ ]:
x=torch.tensor(3.0,requires_grad=True)

In [ ]:
print(x)

tensor(3., requires_grad=True)


In [ ]:
y=x**2

In [ ]:
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(6.)

In [ ]:
import math
def dz_dx(x):

  return 2*x*math.cos(x**2)

In [ ]:
dz_dx(3)

-5.466781571308061

In [ ]:
x=torch.tensor(3.0,requires_grad=True)

In [ ]:
y=x**2

In [ ]:
y.backward()

In [ ]:
z=torch.sin(y)

In [ ]:
x

tensor(3., requires_grad=True)

In [ ]:
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [ ]:
z =torch.sin(x)  # Recompute forward pass
z.backward()


In [ ]:
x.grad

tensor(5.0100)

In [ ]:
import torch
x=torch.tensor(6.7)
y=torch.tensor(0.0)

w=torch.tensor(1.0)
b=torch.tensor(0.0)

In [ ]:
def binary_cross_entropy_loss(prediction,target):
  epsilon=1e-8
  prediction=torch.clamp(prediction,epsilon,1-epsilon)
  return -(target*torch.log(prediction)+(1-target)*torch.log(1-prediction))

In [ ]:
z=w*x+b
y_pred=torch.sigmoid(x)

loss=binary_cross_entropy_loss(y_pred,y)

In [ ]:
dloss_dy_pred=(y_pred-y)/(y_pred*(1-y_pred))
dy_pred_dz=y_pred*(1-y_pred)


dz_dw=x
dz_db=1

dl_dw=dloss_dy_pred*dy_pred_dz*dz_dw
dl_db=dloss_dy_pred*dy_pred_dz*dz_db

In [ ]:
print(f"{dl_dw}")
print(f"{dl_db}")

6.691762447357178
0.998770534992218


In [ ]:
x=torch.tensor(6.7)
y=torch.tensor(0.0)


In [ ]:
w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [ ]:
w


tensor(1., requires_grad=True)

In [ ]:
b

tensor(0., requires_grad=True)

In [ ]:
z=w*x+b

In [ ]:
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [ ]:
y_pred=torch.sigmoid(z)

In [ ]:
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [ ]:
loss=binary_cross_entropy_loss(y_pred,y)

In [ ]:
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [ ]:
loss.backward()

In [ ]:
print(w.grad)

tensor(6.6918)


In [ ]:
print(b.grad)

tensor(0.9988)


In [ ]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)

In [ ]:
y=(x**2).mean()

In [ ]:
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [ ]:
import numpy as np
import pandas as pd
import torch

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)

In [ ]:
df.shape

(569, 31)

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
X_train,X_test,y_test,y_train=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [ ]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
y_test

48     B
545    B
285    B
82     M
333    B
      ..
51     B
113    B
121    M
464    B
33     M
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [ ]:
y_train

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1])

In [ ]:
y_test

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,

In [ ]:
X_train_tensors=torch.from_numpy(X_train)
X_test_tensors=torch.from_numpy(X_test)
y_train_tensors=torch.from_numpy(y_train)
y_test_tensors=torch.from_numpy(y_test)

In [ ]:
X_test_tensors

tensor([[ 0.0921, -1.3481,  0.0528,  ..., -0.0736,  0.2944, -1.2839],
        [ 0.5356,  1.1026,  0.5289,  ..., -0.0248, -0.1261, -1.1648],
        [-0.0518,  0.0854, -0.1102,  ..., -0.8333, -0.6181, -0.8189],
        ...,
        [-0.4952,  0.6981, -0.4860,  ..., -0.4818, -1.0253,  0.3845],
        [ 0.1656,  0.8057,  0.2179,  ..., -0.0461, -1.0420, -0.2130],
        [ 1.2991,  0.6256,  1.2311,  ...,  0.3719,  0.3725, -0.4314]],
       dtype=torch.float64)

In [ ]:
class mysimpleNN():
  def __init__(self,X):

    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True) # Corrected the spelling of requires_grad and its position.
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True) # Corrected the spelling of requires_grad and its position.

  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilon=1e-8
    prediction=torch.clamp(y_pred,epsilon,1-epsilon)
    return -(y_train_tensors*torch.log(prediction)+(1-y_train_tensors)*torch.log(1-prediction)).mean()


In [ ]:
learning_rate=0.1
epochs=25

In [ ]:
import torch
import torch.nn as nn

class Model(nn.Module):  # Fixed class name (Moddel -> Model)
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),  # Input to Hidden Layer (5 -> 3)
            nn.ReLU(),  # Activation Function
            nn.Linear(3, 1),  # Hidden to Output Layer (3 -> 1)
            nn.Sigmoid()  # Activation Function for Output
        )

    def forward(self, features):
        return self.network(features)  # Forward pass using nn.Sequential

# Example usage:
model = Model(num_features=5)
print(model)


Model(
  (network): Sequential(
    (0): Linear(in_features=5, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=1, bias=True)
    (3): Sigmoid()
  )
)


In [ ]:
features=torch.rand(10,5)
model=Model(features.shape[1])
model(features)


tensor([[0.5302],
        [0.5645],
        [0.5804],
        [0.5745],
        [0.5374],
        [0.5487],
        [0.5539],
        [0.5536],
        [0.5538],
        [0.5649]], grad_fn=<SigmoidBackward0>)

In [ ]:
loss_function=nn.BCELoss()

In [ ]:
class mysimpleNN(nn.Module): # Inherit from nn.Module
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
        # Explicitly set the weight and bias data types to float64
        self.linear.weight = nn.Parameter(self.linear.weight.type(torch.float64))
        self.linear.bias = nn.Parameter(self.linear.bias.type(torch.float64))

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out # Add return statement here

    def loss_function(self, y_pred, y):
        epsilon = 1e-8
        prediction = torch.clamp(y_pred, epsilon, 1 - epsilon)
        return -(y * torch.log(prediction) + (1 - y) * torch.log(1 - prediction)).mean()

# Ensure X_train_tensors is also float64
X_train_tensors = X_train_tensors.type(torch.float64)

# ... (rest of your code) ...

model=mysimpleNN(X_train_tensors.shape[1])

# Optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
    y_pred = model(X_train_tensors)
    print(y_pred)

    loss = model.loss_function(y_pred, y_train_tensors)
    print(f"epoch:{epoch+1} loss:{loss.item()}")
    optimizer.zero_grad()
    loss.backward()

    # Update weights using the optimizer
    optimizer.step()
      # Reset gradients

Streaming output truncated to the last 5000 lines.
        [0.2768],
        [0.3334],
        [0.3273],
        [0.3514],
        [0.4751],
        [0.3999],
        [0.3750],
        [0.4249],
        [0.3473],
        [0.3543],
        [0.3485],
        [0.4854],
        [0.2690],
        [0.4444],
        [0.3477],
        [0.2927],
        [0.3893],
        [0.3425],
        [0.4120],
        [0.3563],
        [0.3948],
        [0.3195],
        [0.3234],
        [0.4252],
        [0.3692],
        [0.4062],
        [0.3052],
        [0.2745],
        [0.3785],
        [0.4101],
        [0.4110],
        [0.3299],
        [0.3266],
        [0.3051],
        [0.4367],
        [0.4339],
        [0.3684],
        [0.3883],
        [0.3448],
        [0.2654],
        [0.3885],
        [0.3950],
        [0.2702],
        [0.4131],
        [0.3634],
        [0.2583],
        [0.3004],
        [0.4792],
        [0.4626],
        [0.2357],
        [0.3707],
        [0.4209],
        [0.30

In [ ]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensors)
  y_pred=(y_pred>=0.5).float()
  accuracy=(y_pred==y_test_tensors).float().mean()
  print(f"accuracy:{accuracy.item()}")

print(y_pred)

accuracy:0.6229034066200256
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
      

In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import torch

In [ ]:
X,y=make_classification(n_samples=10,n_features=2,n_classes=2,n_informative=2,n_redundant=0,random_state=42)

In [ ]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [ ]:
X.shape

(10, 2)

In [ ]:
y


array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [ ]:
y.shape

(10,)

In [ ]:
X=torch.tensor(X,dtype=torch.float64)
y=torch.tensor(y,dtype=torch.float64)

In [ ]:
from torch.utils.data import Dataset,DataLoader

In [ ]:
class CD(Dataset):

  def  __init__(self,features,labels):
    self.features=features
    self.labels=labels


  def __len__(self):

    return self.features.shape[0]


  def __getitem__(self,index):
    return self.features[index],self.labels[index]

In [ ]:
dataset=CD(X,y)

In [ ]:
dataset[0]

(tensor([ 1.0683, -0.9701], dtype=torch.float64),
 tensor(1., dtype=torch.float64))

In [ ]:
len(dataset)

10

In [ ]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=True)

In [ ]:
for batch_features,batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)

tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]], dtype=torch.float64)
tensor([0., 1.], dtype=torch.float64)
tensor([[ 1.8997,  0.8344],
        [-0.7206, -0.9606]], dtype=torch.float64)
tensor([1., 0.], dtype=torch.float64)
tensor([[ 1.0683, -0.9701],
        [-0.5872, -1.9717]], dtype=torch.float64)
tensor([1., 0.], dtype=torch.float64)
tensor([[ 1.7273, -1.1858],
        [-2.8954,  1.9769]], dtype=torch.float64)
tensor([1., 0.], dtype=torch.float64)
tensor([[ 1.7774,  1.5116],
        [-1.1402, -0.8388]], dtype=torch.float64)
tensor([1., 0.], dtype=torch.float64)


In [ ]:
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset,DataLoader
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

In [ ]:
torch.manual_seed(42)
df=pd.read_csv('fmnist_small.csv')
df.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      9       0       0       0       0       0       0       0       0   
1      7       0       0       0       0       0       0       0       0   
2      0       0       0       0       0       0       1       0       0   
3      8       0       0       0       0       0       0       0       0   
4      8       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         7         0        50       205       196   
1       0  ...         0         0         0         0         0         0   
2       0  ...       142       142       142        21         0         3   
3       0  ...         0         0         0         0         0         0   
4       0  ...       213       203       174       151       188        10   

   pixel781  pixel782  pixel783  pixel784  
0       213       165         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [ ]:
X=df.iloc[:,1: ].values
y=df.iloc[:,0 ].values

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train.shape

(4800, 784)

In [ ]:
X_train=X_train/255.0
X_test=X_test/255.0

In [ ]:
X_train

array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.0627451, 0.       ,
        0.       ]])

In [ ]:
class CustomDataset(Dataset):

  def __init__(self,features,labels):
    self.features=torch.tensor(features,dtype=torch.float64).reshape(-1,1,28,28) # Change data type to torch.float64
    self.labels=torch.tensor(features,dtype=torch.long)


  def __len__(self):
    return len(self.features)


  def __getitem__(self,index):
    return self.features[index],self.labels[index]

In [ ]:
train_dataset=CustomDataset(X_train,y_train)
test_dataset=CustomDataset(X_test,y_test)

In [ ]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=False)

In [ ]:
class MyNN(nn.Module):
    def __init__(self, input_features):
        super().__init__()

        self.features = nn.Sequential(
            nn.Conv2d(input_features, 32, kernel_size=3, padding='same'),
            nn.ReLU(),
            nn.BatchNorm2d(32),  # BatchNorm2d should match the number of output channels of the previous layer
            nn.MaxPool2d(kernel_size=2, stride=2),

            nn.Conv2d(32, 64, kernel_size=3, padding='same'),
            nn.ReLU(),
            nn.BatchNorm2d(64),  # BatchNorm2d should match the number of output channels of the previous layer (64 in this case)
            nn.MaxPool2d(kernel_size=2, stride=2),
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(7 * 7 * 64, 128), # Changed input features to 7 * 7 * 64 to match flattened output of features
            nn.ReLU(),
            nn.Dropout(p=0.4),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(p=0.4),
            nn.Linear(64, 10)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x

In [ ]:
epochs=100
learning_rate=0.1

In [ ]:
mode=MyNN(1)
criterion=nn.CrossEntropyLoss()
optimizer=optim.SGD(mode.parameters(),lr=learning_rate)

In [ ]:
# ipython-input-275-56fa7afd1a4b
for epoch in range(epochs): # Changed epochs to epoch for correct iteration
  total_loss=0
  for batch_features,batch_labels in train_loader:

    outputs=model.forward(batch_features) # Changed out to outputs and used model
    loss=criterion(outputs,batch_labels) # Changed outputs to match previous line
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    total_loss+=loss.item()

  print(f"epoch:{epoch+1} loss:{total_loss/len(train_loader)}") # Changed epoch to match loop variable

RuntimeError: mat1 and mat2 shapes cannot be multiplied (896x28 and 30x1)

In [ ]:
vice =torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device:{device}")

Using device:cuda


In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset,DataLoader
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
# %%
torch.manual_seed(42)
df=pd.read_csv('fmnist_small.csv')
df.head()
# %%
X=df.iloc[:,1: ].values
y=df.iloc[:,0 ].values
# %%
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
# %%
X_train.shape
# %%
# Convert X_train and X_test to float32
X_train=X_train/255.0
X_train = X_train.astype(np.float32)  # Convert to float32
X_test=X_test/255.0
X_test = X_test.astype(np.float32)  # Convert to float32
# %%
X_train
# %%
class CustomDataset(Dataset):

  def __init__(self,features,labels):
    self.features=torch.tensor(features,dtype=torch.float32) # Data type should match
    self.labels=torch.tensor(labels,dtype=torch.long) # Corrected to use labels


  def __len__(self):
    return len(self.features)


  def __getitem__(self,index):
    return self.features[index],self.labels[index]
# %%
train_dataset=CustomDataset(X_train,y_train)
test_dataset=CustomDataset(X_test,y_test)
# %%
train_loader=DataLoader(train_dataset,batch_size=128,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=128,shuffle=False)
# %%
class MyNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(num_features, 128),  # First hidden layer: 128 neurons
            nn.BatchNorm1d(128),  # Batch normalization
            nn.ReLU(),
            nn.Dropout(p=0.3),
            nn.Linear(128, 64),
            nn.BatchNorm1d(64), # Third hidden layer: 64 neurons
            nn.ReLU(),
            nn.Dropout(p=0.3),
            nn.Linear(64, 10)  # Output layer: 10 neurons (for 10 classes)
        )

    def forward(self, x):
        return self.model(x)

# %%
epochs=100
learning_rate=0.1
# %%
model=MyNN(X_train.shape[1]) # Changed 'mode' to 'model' to match usage
criterion=nn.CrossEntropyLoss()
optimizer=optim.SGD(model.parameters(),lr=learning_rate,weight_decay=1e-4)
# %%
for epoch in range(epochs): # Changed 'epochs' to 'epoch' for iteration
  for batch_features,batch_labels in train_loader:

    outputs=model.forward(batch_features) # Changed 'out' to 'outputs' to match usage
    loss=criterion(outputs,batch_labels) # Use 'outputs' instead of undefined 'out'
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

In [ ]:
mode.eval()

MyNN(
  (features): Sequential(
    (0): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=same)
    (1): ReLU()
    (2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=same)
    (5): ReLU()
    (6): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (classifier): Sequential(
    (0): Flatten(start_dim=1, end_dim=-1)
    (1): Linear(in_features=3136, out_features=128, bias=True)
    (2): ReLU()
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): ReLU()
    (6): Dropout(p=0.4, inplace=False)
    (7): Linear(in_features=64, out_features=10, bias=True)
  )
)

In [ ]:
total = 0 #  keeps track of total data points
correct = 0 #  keeps track of correct predictions


with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    outputs = mode(batch_features)
    _, predicted = torch.max(outputs, 1)

    total += batch_labels.size(0) # Add the batch size instead of the data
    correct += (predicted == batch_labels).sum().item()

accuracy = 100 * correct / total
print(f"Test Accuracy: {accuracy:.2f}%")

RuntimeError: running_mean should contain 64 elements not 32

In [ ]:
import torch
from torch.utils.data import DataLoader, random_split
from torchvision import datasets, transforms

# Define transformations for image datasets
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))  # Normalize images
])

# Download and prepare dataset (e.g., MNIST)
dataset = datasets.MNIST(root="./data", train=True, transform=transform, download=True)

# Split dataset into training and validation sets
train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

# Create DataLoaders
batch_size = 32
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

print("Data loaders initialized successfully!")


In [ ]:
class MyNN(nn.Module):

  def __init__(self,input_dim,output_dim,num_hidden_layers,neurons_per_layer):

    super().__init__()
    layers=[]
    for i in range(num_hidden_layers):
      layers.append(nn.Linear(input_dim,neurons_per_layer))
      layers.append(nn.BatchNorm1d(neurons_per_layer))
      layers.append(nn.ReLU())

      layers.append(nn.Dropout(p=0.3))
      input_dim=neurons_per_layer

    layers.append(nn.Linear(neurons_per_layer,output_dim))

    self.model=nn.Sequential(*layers)
    self.input_dim=input_dim
    self.output_dim=output_dim
    self.num_hidden_layers=num_hidden_layers
    self.neurons_per_layer=neurons_per_layer

  def forward(self,x):
    return self.model(x)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import optuna
from torch.utils.data import DataLoader, random_split
from torchvision import datasets, transforms

# ----------------------- Define Neural Network -----------------------
class MyNN(nn.Module):
    def __init__(self, input_dim, output_dim, num_hidden_layers, neurons_per_layer):
        super(MyNN, self).__init__()

        layers = [nn.Linear(input_dim, neurons_per_layer), nn.ReLU()]

        for _ in range(num_hidden_layers - 1):
            layers.append(nn.Linear(neurons_per_layer, neurons_per_layer))
            layers.append(nn.ReLU())

        layers.append(nn.Linear(neurons_per_layer, output_dim))  # Output layer

        self.model = nn.Sequential(*layers)

    def forward(self, x):
        return self.model(x)

# ----------------------- Prepare Data -----------------------
# Transform images to tensors & normalize
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

# Load dataset (e.g., MNIST)
dataset = datasets.MNIST(root="./data", train=True, transform=transform, download=True)

# Split into training & validation sets
train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

# Define DataLoaders
batch_size = 32
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

# ----------------------- Objective Function for Optuna -----------------------
def objective(trial):
    # Hyperparameter tuning
    num_hidden_layers = trial.suggest_int("num_hidden_layers", 1, 5)
    neurons_per_layer = trial.suggest_int("neurons_per_layer", 16, 128, step=8)
    learning_rate = trial.suggest_float("learning_rate", 1e-5, 1e-1, log=True)

    # Model definition
    input_dim = 784  # Flattened 28x28 input
    output_dim = 10  # MNIST has 10 classes
    model = MyNN(input_dim, output_dim, num_hidden_layers, neurons_per_layer)

    # Loss function & optimizer
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=learning_rate, weight_decay=1e-4)

    # Training loop
    epochs = 5  # Reduce epochs for fast tuning
    model.train()
    for epoch in range(epochs):
        for batch_features, batch_labels in train_loader:
            batch_size = batch_features.shape[0]
            batch_features = batch_features.view(batch_size, -1)  # Flatten input

            outputs = model(batch_features)
            loss = criterion(outputs, batch_labels)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

    # Validation loop
    val_loss = 0.0
    model.eval()
    with torch.no_grad():
        for val_features, val_labels in val_loader:
            batch_size = val_features.shape[0]
            val_features = val_features.view(batch_size, -1)  # Flatten validation input

            val_outputs = model(val_features)
            val_loss += criterion(val_outputs, val_labels).item()

    return val_loss / len(val_loader)  # Return avg validation loss

# ----------------------- Run Optuna Study -----------------------
study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=10)

# Print best parameters
print("Best hyperparameters:", study.best_params)


ModuleNotFoundError: No module named 'optuna'

In [ ]:
df.shape

(6000, 785)